language: cpp
sudo: required
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always
git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-5
      env: COMPILER=g++-5

    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
      env: COMPILER=g++-6

before_script:
  - ${compiler} --version
  - ${cmake} --version

script:
  - mkdir -p debug_build
  - cd debug_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -DCMAKE_BUILD_TYPE=Debug
  - make -j2
  - ctest --output-on-failure
  - cd ..
  - mkdir -p release_build
  - cd release_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -DCMAKE_BUILD_TYPE=Release
  - make -j2
  - ctest --output-on_failure
